### ISSUE TITLE
Fix display of remaining balance before recalculation of balance

### ISSUE THREAD

**Issue by ctzeyong** [AY2425S1-CS2113-W14-3/tp#215]

**Comment by limkongkiat** [comment]
![image](https://github.com/user-attachments/assets/87a1f67d-312e-423a-ad05-f783f0eae7bd)

**Comment by limkongkiat** [comment]
![image](https://github.com/user-attachments/assets/93a63acb-9a4f-401b-b406-73ae96c4911e)
