### ISSUE TITLE
[PE-D][Tester B] [UG] Edit Transaction Description Parameter stated as "shouldn't be blank" but possible to execute edit with blank description

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W14-3/tp#238]
![empty des.PNG](https://raw.githubusercontent.com/RCPilot1604/ped/main/files/b4859f9f-aaca-4699-8d66-2f674d207933.PNG)

![edit index instructions.PNG](https://raw.githubusercontent.com/RCPilot1604/ped/main/files/1a9a04c1-4915-4f6a-a2cd-0c6c81773555.PNG)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: RCPilot1604/ped#3

**Comment by limkongkiat** [comment]
@tsoudibi Edit UG section
@kestryix same issue as everything else
